# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWorker',
            fields=[
                ('mainuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_social_worker', models.BooleanField(default=True, verbose_name='is Social Worker')),
            ],
            options={
                'abstract': False,
            },
            bases=('authe.mainuser',),
        ),
    ]
