# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_socialworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionHead',
            fields=[
                ('mainuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_commission_head', models.BooleanField(default=True, verbose_name='is Commission Head')),
            ],
            options={
                'abstract': False,
            },
            bases=('authe.mainuser',),
        ),
    ]
