# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20181124_1716'),
        ('authe', '0003_commissionhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalCommission',
            fields=[
                ('mainuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_departmental_commission', models.BooleanField(default=True, verbose_name='is Departmental Commission')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_for_commission', to='department.Department')),
            ],
            options={
                'verbose_name': 'Departmental Commission',
                'verbose_name_plural': 'Departmental Commissions',
            },
            bases=('authe.mainuser',),
        ),
        migrations.CreateModel(
            name='DepartmentalWorker',
            fields=[
                ('mainuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_departmental_worker', models.BooleanField(default=True, verbose_name='is Departmental Worker')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_for_worker', to='department.Department')),
            ],
            options={
                'verbose_name': 'Departmental Worker',
                'verbose_name_plural': 'Departmental Worker',
            },
            bases=('authe.mainuser',),
        ),
        migrations.AlterModelOptions(
            name='commissionhead',
            options={'verbose_name': 'Commission Head', 'verbose_name_plural': 'Commission Heads'},
        ),
        migrations.AlterModelOptions(
            name='socialworker',
            options={'verbose_name': 'Social Worker', 'verbose_name_plural': 'Social Workers'},
        ),
    ]
