# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_auto_20181124_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionhead',
            name='is_commission_head',
            field=models.BooleanField(default=False, verbose_name='is Commission Head'),
        ),
        migrations.AlterField(
            model_name='departmentalcommission',
            name='is_departmental_commission',
            field=models.BooleanField(default=False, verbose_name='is Departmental Commission'),
        ),
        migrations.AlterField(
            model_name='departmentalworker',
            name='is_departmental_worker',
            field=models.BooleanField(default=False, verbose_name='is Departmental Worker'),
        ),
        migrations.AlterField(
            model_name='socialworker',
            name='is_social_worker',
            field=models.BooleanField(default=False, verbose_name='is Social Worker'),
        ),
    ]
