# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20181124_1724'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('authe', '0007_auto_20181124_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionhead',
            name='mainuser_ptr',
        ),
        migrations.RemoveField(
            model_name='departmentalcommission',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentalcommission',
            name='mainuser_ptr',
        ),
        migrations.RemoveField(
            model_name='departmentalworker',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentalworker',
            name='mainuser_ptr',
        ),
        migrations.RemoveField(
            model_name='socialworker',
            name='mainuser_ptr',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'User'), (1, 'Social Worker'), (2, 'Commission Head'), (3, 'Departmental Worker'), (4, 'Departmental Commission')], default=0, verbose_name='Password type'),
        ),
        migrations.DeleteModel(
            name='CommissionHead',
        ),
        migrations.DeleteModel(
            name='DepartmentalCommission',
        ),
        migrations.DeleteModel(
            name='DepartmentalWorker',
        ),
        migrations.DeleteModel(
            name='SocialWorker',
        ),
    ]
