# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20181124_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='department',
            name='timestamp',
            field=models.BigIntegerField(default=1543058195894, verbose_name='Department timestamp'),
        ),
    ]
