# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20181124_1716'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=555, verbose_name='Full name')),
                ('iin', models.CharField(max_length=15, verbose_name='IIN')),
                ('address', models.CharField(max_length=1000, verbose_name='Address')),
                ('address_residential', models.CharField(max_length=1000, verbose_name='Residential address')),
                ('contacts', models.CharField(max_length=100, verbose_name='Contacts')),
                ('status', models.CharField(max_length=1000, verbose_name='Status')),
                ('place_of_work', models.CharField(max_length=1000, verbose_name='Place of work')),
                ('occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('income', models.CharField(max_length=1000, verbose_name='Income')),
                ('health_condition', models.CharField(max_length=1000000, verbose_name='Health condition')),
                ('description', models.CharField(max_length=1000000, verbose_name='Problem description')),
                ('needs', models.CharField(max_length=1000000, verbose_name='Needs')),
                ('place', models.CharField(max_length=1000, verbose_name='Place of gathering')),
                ('datetime', models.BigIntegerField(default=1543058195905, verbose_name='Time of gathering')),
                ('problems', models.CharField(max_length=1000000, verbose_name='Problems')),
                ('is_approved_by_social_worker', models.BooleanField(default=False, verbose_name='Approved by social worker')),
                ('deadline', models.BigIntegerField(default=1543058195905, verbose_name='Deadline')),
                ('is_approved_by_departmental_worker', models.BooleanField(default=False, verbose_name='Approved by departmental worker')),
                ('is_approved_by_departmental_commission', models.BooleanField(default=False, verbose_name='Approved by departmental commission')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='CaseDepartmentPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_for_department_priority', to='case.Case')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_for_case', to='department.Department')),
            ],
            options={
                'verbose_name': 'CaseDepartmentPriority',
                'verbose_name_plural': 'CaseDepartmentPriorities',
            },
        ),
        migrations.CreateModel(
            name='CasetoCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case1', to='case.Case')),
                ('case2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case2', to='case.Case')),
            ],
            options={
                'verbose_name': 'Case to Case',
                'verbose_name_plural': 'Case to cases',
            },
        ),
        migrations.CreateModel(
            name='ResultCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(default='result', max_length=100, verbose_name='Type of info')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_for_result', to='case.Case')),
            ],
            options={
                'verbose_name': 'Result Case',
                'verbose_name_plural': 'Result Cases',
            },
        ),
        migrations.CreateModel(
            name='SolutionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(default='solution', max_length=100, verbose_name='Type of info')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_for_solution', to='case.Case')),
            ],
            options={
                'verbose_name': 'Solution Case',
                'verbose_name_plural': 'Solution Cases',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.BigIntegerField(default=1543058195903, verbose_name='Priority timestamp'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='timestamp',
            field=models.BigIntegerField(default=1543058195902, verbose_name='Priority timestamp'),
        ),
        migrations.AddField(
            model_name='solutioncase',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_solution', to='case.Comment'),
        ),
        migrations.AddField(
            model_name='solutioncase',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_for_solution', to='department.Department'),
        ),
        migrations.AddField(
            model_name='resultcase',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_result', to='case.Comment'),
        ),
        migrations.AddField(
            model_name='resultcase',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_for_result', to='department.Department'),
        ),
        migrations.AddField(
            model_name='casedepartmentpriority',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_for_case', to='case.Priority'),
        ),
    ]
