# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20181124_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetocase',
            name='case1',
        ),
        migrations.RemoveField(
            model_name='casetocase',
            name='case2',
        ),
        migrations.DeleteModel(
            name='CasetoCase',
        ),
    ]
