# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20181124_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='parent_case',
            field=models.IntegerField(null=True, verbose_name='Parent case'),
        ),
    ]
