# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_case_parent_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultcase',
            name='department',
        ),
        migrations.RemoveField(
            model_name='solutioncase',
            name='department',
        ),
        migrations.AddField(
            model_name='resultcase',
            name='timestamp',
            field=models.BigIntegerField(default=0, verbose_name='Result Case timestamp'),
        ),
        migrations.AddField(
            model_name='solutioncase',
            name='timestamp',
            field=models.BigIntegerField(default=0, verbose_name='Solution Case timestamp'),
        ),
    ]
